AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SecretX:
    Type: String
    NoEcho: true
  SecretY:
    Type: String
    NoEcho: true
  RotationFunctionArn:
    Type: String

Resources:
  SecretA:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MySecretA
      SecretString: !Sub '{"username":"${SecretX}","password":${SecretY}"}'
      Tags:
        - Key: AppName
          Value: App

  SecretB:
    Type: AWS::SecretsManager::Secret
    DependsOn: SecretA
    Properties:
      Name: MySecretB
      Tags:
        - Key: AppName
          Value: App

  SecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId: !Ref SecretB
      RotationLambdaARN: !Ref RotationFunctionArn
      RotationRules:
        AutomaticallyAfterDays: 1
